{
 "title": "CPU Utilization Details",
 "tags": [
  "Percona",
  "OS"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({__name__=~'up'}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "$instance - Overall CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max(avg by (instance,mode) ((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\"}[5m]),1)) ))*100 or (max_over_time(node_cpu_average{instance=~\"$instance\",mode=~\"user|system|wait|steal|irq\"}[$interval]) or max_over_time(node_cpu_average{instance=~\"$instance\", mode=~\"user|system|wait|steal|irq\"}[5m]))),100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "clamp_max(max by () ((sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )*100) or (max_over_time(node_cpu_average{instance=~\"$instance\", mode=~\"user|system|steal|irq\"}[$interval]) or max_over_time(node_cpu_average{instance=~\"$instance\", mode=~\"user|system|steal|irq\"}[5m]))),100)",
     "legendFormat": "Max Core Utilization"
    }
   ]
  },
  {
   "title": "$instance - Current CPU Threads Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max(avg by () ((sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1))*100 )) or max_over_time(node_cpu_average{instance=~\"$instance\", mode!=\"total\",mode!=\"idle\", mode!=\"wait\"}[5m])) ,100)",
     "legendFormat": "Avg"
    },
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max((sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\",mode!=\"iowait\"}[5m])*100,100)) )) or sum by (cpu) (max_over_time(node_cpu_average{instance=~\"$instance\", mode!=\"total\",mode!=\"idle\", mode!=\"wait\"}[5m])) ,100)",
     "legendFormat": " {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Threads Frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance - CPU Threads Frequency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "avg by (instance,cpu) (max_over_time(node_cpu_frequency_hertz{instance=~\"$instance\"}[$interval]) or max_over_time(node_cpu_frequency_hertz{instance=~\"$instance\"}[5m]))",
       "legendFormat": "cpu_{{cpu}}"
      },
      {
       "expr": "avg(max_over_time(node_cpu_frequency_hertz{instance=~\"$instance\"}[$interval]) or max_over_time(node_cpu_frequency_hertz{instance=~\"$instance\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Current CPU Cores Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance - Current CPU Cores Temperature",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "avg(label_replace(sum by (sensor,instance,chip,cpu) ((node_hwmon_temp_celsius{instance=~\"$instance\"})) * on(sensor) group_left(cpu) (sum by (sensor,instance,cpu) (label_replace(node_hwmon_sensor_label{instance=~\"$instance\",label=~\"core.*\"},\"cpu\", \"$1\", \"label\", \"core_(.*)\"))),\"chip\", \"$2\", \"chip\", \"(.*)_coretemp_(.*)\"))",
       "legendFormat": "Avg"
      },
      {
       "expr": "(label_replace(sum by (sensor,instance,chip,cpu) ((node_hwmon_temp_celsius{instance=~\"$instance\"})) * on(sensor) group_left(cpu) (sum by (sensor,instance,cpu) (label_replace(node_hwmon_sensor_label{instance=~\"$instance\",label=~\"core.*\"},\"cpu\", \"$1\", \"label\", \"core_(.*)\"))),\"chip\", \"$2\", \"chip\", \"(.*)_coretemp_(.*)\"))",
       "legendFormat": " cpu{{chip}}-core{{cpu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Overall CPU Threads Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "All Cores - total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(sum by () ((avg by (mode) ( \n(clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100 or \nsum by () (\navg_over_time(node_cpu_average{instance=~\"$instance\",mode!=\"total\",mode!=\"idle\"}[$interval]) or \navg_over_time(node_cpu_average{instance=~\"$instance\",mode!=\"total\",mode!=\"idle\"}[5m])) unless\n(avg_over_time(node_cpu_average{instance=~\"$instance\",mode=\"total\",job=\"rds-basic\"}[$interval]) or \navg_over_time(node_cpu_average{instance=~\"$instance\",mode=\"total\",job=\"rds-basic\"}[5m]))\n),100)"
    }
   ]
  },
  {
   "title": "All Cores - user",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(avg by (instance,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=~\"$instance\", mode=\"user\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$instance\", mode=\"user\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - system",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(avg by (instance,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"system\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=~\"$instance\", mode=\"system\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$instance\", mode=\"system\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - iowait",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(avg by (instance,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=~\"$instance\", mode=\"wait\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$instance\", mode=\"wait\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - steal",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(avg by (instance,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"steal\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=~\"$instance\", mode=\"steal\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$instance\", mode=\"steal\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - other",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100) or (sum(avg_over_time(node_cpu_average{instance=~\"$instance\", mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[$interval])) or sum(avg_over_time(node_cpu_average{instance=~\"$instance\", mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[5m])))),100) "
    }
   ]
  },
  {
   "title": "CPU Threads Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Per Core CPU Threads Usage",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "Per CPU usage Information shows  usage for each CPU (Virtual) core.  The Current (most recent) numbers are shown together with history as sparkline"
   }
  },
  { "title": "$cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "cpu" },
  {
   "title": "$cpu - total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(\nsum by (cpu) (\n(avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100) or \nsum by () (\navg_over_time(node_cpu_average{instance=~\"$instance\",mode!=\"total\",mode!=\"idle\"}[$interval]) or \navg_over_time(node_cpu_average{instance=~\"$instance\",mode!=\"total\",mode!=\"idle\"}[5m])) unless\n(avg_over_time(node_cpu_average{instance=~\"$instance\",mode=\"total\",job=\"rds-basic\"}[$interval]) or \navg_over_time(node_cpu_average{instance=~\"$instance\",mode=\"total\",job=\"rds-basic\"}[5m]))\n,100)"
    }
   ]
  },
  {
   "title": "$cpu - user",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(avg by (instance,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",cpu=\"$cpu\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",cpu=\"$cpu\",mode=\"user\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=~\"$instance\", cpu=\"All\", mode=\"user\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$instance\", cpu=\"All\", mode=\"user\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - system",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(avg by (instance,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",cpu=\"$cpu\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",cpu=\"$cpu\",mode=\"system\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=~\"$instance\", cpu=\"All\", mode=\"system\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$instance\", cpu=\"All\", mode=\"system\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - iowait",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(avg by (instance,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",cpu=\"$cpu\",mode=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",cpu=\"$cpu\",mode=\"iowait\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=~\"$instance\", cpu=\"All\", mode=\"wait\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$instance\", cpu=\"All\", mode=\"wait\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - steal",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(avg by (instance,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",cpu=\"$cpu\",mode=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",cpu=\"$cpu\",mode=\"steal\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=~\"$instance\", cpu=\"All\", mode=\"steal\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$instance\", cpu=\"All\", mode=\"steal\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - other",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((sum by (instance) (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$instance\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$instance\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100) or (sum(avg_over_time(node_cpu_average{instance=~\"$instance\", cpu=\"All\",mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[$interval])) or sum(avg_over_time(node_cpu_average{instance=~\"$instance\",cpu=\"All\",mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[5m])))),100)"
    }
   ]
  }
 ]
}