{
 "title": "MySQL Table Details",
 "tags": [
  "MySQL",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values(mysql_up{service_name=~\"$service_name\"}, node_name)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(mysql_info_schema_table_version, service_name)"
   },
   {
    "name": "version",
    "query": "query_result(mysql_version_info{service_name=~\"$service_name\"})"
   },
   {
    "name": "crop_service",
    "label": "Service Name",
    "query": "label_values(mysql_up{service_name=~\"$service_name\"}, service_name)"
   },
   {
    "name": "crop_host",
    "label": "Crop Node Name",
    "query": "label_values(mysql_up{node_name=\"$node_name\"},node_name)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   },
   {
    "name": "username",
    "label": "Username",
    "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Largest Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Largest Tables by Row Count",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "topk(10, avg by (service_name,schema,table) (sum(mysql_info_schema_table_rows{service_name=~\"$service_name\"}) by (service_name, schema, table))) > 0",
     "legendFormat": "{{service_name}}.{{ schema }}.{{ table }}"
    }
   ]
  },
  {
   "title": "Largest Tables by Size",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "topk(10, avg by (service_name,schema,table) (sum(mysql_info_schema_table_size{service_name=~\"$service_name\", component!=\"data_free\"}) by (schema, table,service_name))) > 0",
     "legendFormat": "{{service_name}}.{{ schema }}.{{ table }}"
    }
   ]
  },
  { "title": "Size - $service_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "service_name" },
  {
   "title": "Total Databases Size - $service_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (sum(max_over_time(mysql_info_schema_table_size{service_name=~\"$service_name\", component!=\"data_free\"}[$interval]) or\nmax_over_time(mysql_info_schema_table_size{service_name=~\"$service_name\", component!=\"data_free\"}[5m])))",
     "legendFormat": "Data + Index Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (sum(max_over_time(mysql_info_schema_table_size{service_name=~\"$service_name\", component=\"data_free\"}[$interval]) or\nmax_over_time(mysql_info_schema_table_size{service_name=~\"$service_name\", component=\"data_free\"}[5m])))",
     "legendFormat": "Freeable Size"
    }
   ]
  },
  {
   "title": "Most Fragmented Tables by Freeable Size - $service_name",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "topk(5, avg by (service_name,schema,table) (sum(mysql_info_schema_table_size{service_name=~\"$service_name\", component=\"data_free\"}) by (schema, table, service_name)))",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  },
  { "title": "Table Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "The next two graphs are available only for [Percona Server](https://www.percona.com/doc/percona-server/5.6/diagnostics/user_stats.html) and [MariaDB](https://mariadb.com/kb/en/mariadb/user-statistics/) and require `userstat` variable turned on."
   }
  },
  { "title": "Rows Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Top Tables by Rows Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, avg by (service_name,schema,table) (rate(mysql_info_schema_table_statistics_rows_read_total{service_name=~\"$service_name\"}[$interval]))>0) or \ntopk(5, avg by (service_name,schema,table) (irate(mysql_info_schema_table_statistics_rows_read_total{service_name=~\"$service_name\"}[5m]))>0)",
     "legendFormat": "{{service_name}} - {{ schema }}.{{ table }}"
    }
   ]
  },
  { "title": "Rows Changed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Top Tables by Rows Changed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, avg by (service_name,schema,table) (rate(mysql_info_schema_table_statistics_rows_changed_total{service_name=~\"$service_name\"}[$interval])>0)) or topk(5, avg by (service_name,schema,table) (irate(mysql_info_schema_table_statistics_rows_changed_total{service_name=~\"$service_name\"}[5m]))>0)",
     "legendFormat": "{{service_name}} - {{ schema }}.{{ table }}"
    }
   ]
  },
  { "title": "Auto Increment Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Top Tables by Auto Increment Usage",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "topk(10, avg by (service_name,schema,table) (mysql_info_schema_auto_increment_column{service_name=~\"$service_name\"} / mysql_info_schema_auto_increment_column_max{service_name=~\"$service_name\"}))",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  },
  {
   "title": "MySQL Summary - $service_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "repeat": "service_name",
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Uptime",
     "type": "singlestat",
     "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 76 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (mysql_global_status_uptime{service_name=~\"$service_name\"})"
      }
     ]
    },
    {
     "title": "Version",
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 76 },
     "content": "<h3 style='color:#e68a00;font-weight:bold;text-align:center'>$version</h3>"
    },
    {
     "title": "Current QPS",
     "type": "singlestat",
     "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 76 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (rate(mysql_global_status_queries{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_queries{service_name=~\"$service_name\"}[5m]))"
      }
     ]
    },
    {
     "title": "File Handlers Used",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 76 },
     "format": "percentunit",
     "valueName": "max",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(sum(max_over_time(mysql_global_status_open_files{service_name=~\"$service_name\"}[$interval])) or sum(max_over_time(mysql_global_status_open_files{service_name=~\"$service_name\"}[5m]))) / (sum\r(max_over_time(mysql_global_variables_open_files_limit{service_name=~\"$service_name\"}[$interval])) or sum(max_over_time(mysql_global_variables_open_files_limit{service_name=~\"$service_name\"}[5m]))\r)"
      }
     ]
    },
    {
     "title": "Table Open Cache Miss Ratio",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 76 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (1-((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[5m]))/((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[5m]))+(rate(mysql_global_status_table_open_cache_misses{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{service_name=~\"$service_name\"}[5m])))))"
      }
     ]
    },
    {
     "title": "Table Open Cache Size",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 76 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (mysql_global_variables_table_open_cache{service_name=~\"$service_name\"})"
      }
     ]
    },
    {
     "title": "Table Definition Cache Size",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 76 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (mysql_global_variables_table_definition_cache{service_name=~\"$service_name\"})"
      }
     ]
    },
    {
     "title": "Service",
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 76 },
     "content": "<h5 style='color:#e68a00;font-weight:bold;text-align:center'><a href=\"/graph/d/mysql-instance-summary/mysql-instance-summary?var-service_name=$service_name\" target=\"_blank\">$crop_service...</h5>"
    },
    {
     "title": "MySQL Connections",
     "type": "graph",
     "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max(max_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[$interval]) or \nmax_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[5m])))",
       "legendFormat": "Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_max_used_connections{service_name=~\"$service_name\"}[$interval]) or \nmax_over_time(mysql_global_status_max_used_connections{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Max Used Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_variables_max_connections{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_variables_max_connections{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Max Connections"
      }
     ]
    },
    {
     "title": "MySQL Client Thread Activity",
     "type": "graph",
     "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "yaxes": [
      { "format": "short", "label": "Threads" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Peak Threads Connected"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Peak Threads Running"
      },
      {
       "expr": "avg by (service_name) (avg_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[$interval]) or \navg_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Avg Threads Running"
      }
     ]
    },
    {
     "title": "MySQL Handlers",
     "type": "graph",
     "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,handler) (rate(mysql_global_status_handlers_total{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_handlers_total{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{ handler }}"
      }
     ]
    },
    {
     "title": "Top Command Counters",
     "type": "graph",
     "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(10, avg by (service_name,command) (rate(mysql_global_status_commands_total{service_name=~\"$service_name\"}[$interval]))>0 or \navg by (service_name,command) (irate(mysql_global_status_commands_total{service_name=~\"$service_name\"}[5m]))>0)",
       "legendFormat": "Com_{{ command }}"
      }
     ]
    },
    {
     "title": "Process States",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,state) (max_over_time(mysql_info_schema_threads{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_info_schema_threads{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "MySQL Network Traffic",
     "type": "graph",
     "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_global_status_bytes_received{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_bytes_received{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_global_status_bytes_sent{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_bytes_sent{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Summary - $node_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "repeat": "node_name",
   "collapsed": true,
   "panels": [
    {
     "title": "System Uptime",
     "type": "singlestat",
     "description": "The parameter shows how long a system has been “up” and running without a shut down or restart.",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 50 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name) ((node_time_seconds{node_name=~\"$node_name\"} - node_boot_time_seconds{node_name=~\"$node_name\"}) or (time() - node_boot_time_seconds{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "singlestat",
     "description": "The system load is a measurement of the computational work the system is performing. Each running process either using or waiting for CPU resources adds 1 to the load.",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 50 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (avg_over_time(node_load1{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_load1{node_name=~\"$node_name\"}[5m]))"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "singlestat",
     "description": "RAM (Random Access Memory) is the hardware in a computing device where the operating system, application programs and data in current use are kept so they can be quickly reached by the device's processor.",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 50 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "singlestat",
     "description": "Percent of Memory Available\nNote: on Modern Linux Kernels amount of Memory Available for application is not the same as Free+Cached+Buffers",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 50 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"}) * 100 or (100 - azure_memory_percent_average{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "singlestat",
     "description": "RAM + SWAP",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 50 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"}+node_memory_SwapTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Disk Space",
     "type": "singlestat",
     "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 50 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (sum(avg(node_filesystem_size_bytes{node_name=~\"$node_name\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype))"
      }
     ]
    },
    {
     "title": "Min Space Available",
     "type": "singlestat",
     "description": "Lowest percent of the disk space available",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 50 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (min(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"}/node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"})*100 or \n(100 - azure_storage_percent_average{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Node",
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 50 },
     "options": {
      "content": "<h5 style='color:#e68a00;font-weight:bold;text-align:center'><a href=\"/graph/d/node-instance-summary/node-summary?var-node_name=$node_name\" target=\"_blank\">$crop_host...</a></h5>"
     },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_global_variables_innodb_buffer_pool_size{service_name=~\"$service_name\"} "
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[5m]))),100))",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "CPU Saturation and Max Core Usage",
     "type": "graph",
     "description": "When a system is running with maximum CPU utilization, the transmitting and receiving threads must all share the available CPU. This will cause data to be queued more frequently to cope with the lack of CPU. CPU Saturation may be measured as the length of a wait queue, or the time spent waiting on the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) ((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or (avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})))",
       "legendFormat": "Normalized CPU Load"
      },
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max CPU Core Utilization"
      }
     ]
    },
    {
     "title": "Disk I/O and Swap Activity",
     "type": "graph",
     "description": "Disk I/O includes read or write or input/output operations involving a physical disk. It is the speed with which the data transfer takes place between the hard disk drive and RAM.\n\nSwap Activity is memory management that involves swapping sections of memory to and from physical storage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "Bps", "label": "Page Out (-) / Page In (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (rate(node_vmstat_pgpgin{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$node_name\"}[5m]) * 1024)",
       "legendFormat": "Disk Reads (Page In)"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) ((rate(node_vmstat_pgpgout{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$node_name\"}[5m]) * 1024))",
       "legendFormat": "Disk Writes (Page Out)"
      },
      {
       "expr": "avg by (node_name) ((rate(node_vmstat_pgpgin{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$node_name\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$node_name\"}[5m]) * 1024))",
       "legendFormat": "Total"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpin{node_name=\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpout{node_name=\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "description": "Network traffic refers to the amount of data moving across a network at a given point in time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (sum(rate(node_network_receive_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{node_name=\"$node_name\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{node_name=\"$node_name\"}[5m])))",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (sum(rate(node_network_transmit_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{node_name=\"$node_name\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{node_name=\"$node_name\"}[5m])))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  }
 ]
}