{
 "title": "Nodes Compare",
 "description": "Dashboard to view multiple servers",
 "tags": [
  "OS_Compare",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values({__name__=~\"node_boot_time_seconds|rdsosmetrics_timestamp\"}, node_name)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_name)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   },
   {
    "name": "username",
    "label": "Username",
    "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "System Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "$node_name - System Info",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "repeat": "node_name",
   "targets": [
    {
     "expr": "node_uname_info{node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "$node_name - System Uptime",
   "type": "singlestat",
   "description": "The parameter shows how long a system has been “up” and running without a shut down or restart.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "repeat": "node_name",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (node_name) (node_time_seconds{node_name=~\"$node_name\"} - node_boot_time_seconds{node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "$node_name - CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
   "repeat": "node_name",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (node_name) ((count(node_cpu_seconds_total{node_name=~\"$node_name\",mode=~\"user\"}) or (1-absent(node_cpu_seconds_total{node_name=~\"$node_name\",mode=~\"user\"}))) + sum(rdsosmetrics_General_numVCPUs{node_name=~\"$node_name\"} or up * 0))"
    }
   ]
  },
  {
   "title": "$node_name - RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "repeat": "node_name",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "$node_name - Saturation Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "repeat": "node_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (node_name) ((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or (avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})))",
     "legendFormat": "Normalized CPU Load"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg by (node_name) (avg_over_time(node_procs_blocked{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_procs_blocked{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "IO Load "
    },
    {
     "expr": "avg by (node_name) (max_over_time(aws_rds_cpu_credit_usage_average{node_name=~\"$node_name\"}[$interval]) or max_over_time(aws_rds_cpu_credit_usage_average{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "CPU Credits Usage"
    }
   ]
  },
  {
   "title": "$node_name - Load Average",
   "type": "graph",
   "description": "The system load is a measurement of the computational work the system is performing. Each running process either using or waiting for CPU resources adds 1 to the load.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "repeat": "node_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (node_name) (max_over_time(node_load1{node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(node_load1{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "LoadAvg 1m"
    },
    {
     "expr": "avg by (node_name) ((count(node_cpu_seconds_total{node_name=~\"$node_name\",mode=~\"user\"}) or (1-absent(node_cpu_seconds_total{node_name=~\"$node_name\",mode=~\"user\"}))) + sum(rdsosmetrics_General_numVCPUs{node_name=~\"$node_name\"} or up * 0))",
     "legendFormat": "VCPUs"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node_name - CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode,node_name) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!~\"idle|\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!~\"idle|\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!~\"idle|\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!~\"idle|\"}[5m]))),100))",
       "legendFormat": "{{mode}}"
      },
      {
       "expr": "clamp_max(max by (node_name) (sum  by (cpu,node_name) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max Core Utilization"
      }
     ]
    },
    {
     "title": "$node_name - CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!~\"idle|\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!~\"idle|\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!~\"idle|\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!~\"idle|\"}[5m]))),100))",
       "legendFormat": "{{mode}}"
      },
      {
       "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max Core Utilization"
      }
     ]
    },
    {
     "title": "$node_name - Interrupts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name) (rate(node_intr_total{node_name=~\"$node_name\"}[$interval]) or irate(node_intr_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Interrupts"
      },
      {
       "expr": "avg by (node_name) ((rate(node_intr_total{node_name=~\"$node_name\"}[$interval]) or irate(node_intr_total{node_name=~\"$node_name\"}[5m])) /scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})))",
       "legendFormat": "Interrupts per VCPU"
      }
     ]
    },
    {
     "title": "$node_name - Interrupts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name) (rate(node_intr_total{node_name=~\"$node_name\"}[$interval]) or irate(node_intr_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Interrupts"
      },
      {
       "expr": "avg by (node_name) ((rate(node_intr_total{node_name=~\"$node_name\"}[$interval]) or irate(node_intr_total{node_name=~\"$node_name\"}[5m])) /scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})))",
       "legendFormat": "Interrupts per VCPU"
      }
     ]
    },
    {
     "title": "$node_name - Context Switches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name) (rate(node_context_switches_total{node_name=~\"$node_name\"}[$interval]) or irate(node_context_switches_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Context Switches"
      },
      {
       "expr": "avg by (node_name) ((rate(node_context_switches_total{node_name=~\"$node_name\"}[$interval]) or irate(node_context_switches_total{node_name=~\"$node_name\"}[5m])) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})))",
       "legendFormat": "Context Switches per Virtual CPU"
      }
     ]
    },
    {
     "title": "$node_name - Context Switches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name) (rate(node_context_switches_total{node_name=~\"$node_name\"}[$interval]) or irate(node_context_switches_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Context Switches"
      },
      {
       "expr": "avg by (node_name) ((rate(node_context_switches_total{node_name=~\"$node_name\"}[$interval]) or irate(node_context_switches_total{node_name=~\"$node_name\"}[5m])) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})))",
       "legendFormat": "Context Switches per Virtual CPU"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node_name - Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "bytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name) (max by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"}) - (max by (node_name) (node_memory_MemFree_bytes{node_name=~\"$node_name\"}) + max by (node_name) (node_memory_Buffers_bytes{node_name=~\"$node_name\"}) + (max by (node_name) (node_memory_Cached_bytes{node_name=~\"$node_name\"}))))",
       "legendFormat": "Used"
      },
      {
       "expr": "avg by (node_name) (max_over_time(node_memory_MemFree_bytes{node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(node_memory_MemFree_bytes{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Free"
      },
      {
       "expr": "avg by (node_name) (max_over_time(node_memory_Buffers_bytes{node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(node_memory_Buffers_bytes{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Buffers"
      },
      {
       "expr": "avg by (node_name) (max by (node_name) (node_memory_Cached_bytes{node_name=~\"$node_name\"}))",
       "legendFormat": "Cached"
      }
     ]
    },
    {
     "title": "$node_name - Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "bytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name) (max(node_memory_MemTotal_bytes{node_name=~\"$node_name\"}) - (max(node_memory_MemFree_bytes{node_name=~\"$node_name\"}) + max(node_memory_Buffers_bytes{node_name=~\"$node_name\"}) + (max(node_memory_Cached_bytes{node_name=~\"$node_name\"}))))",
       "legendFormat": "Used"
      },
      {
       "expr": "avg by (node_name) (max_over_time(node_memory_MemFree_bytes{node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(node_memory_MemFree_bytes{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Free"
      },
      {
       "expr": "avg by (node_name) (max_over_time(node_memory_Buffers_bytes{node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(node_memory_Buffers_bytes{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Buffers"
      },
      {
       "expr": "avg by (node_name) (max(node_memory_Cached_bytes{node_name=~\"$node_name\"}))",
       "legendFormat": "Cached"
      }
     ]
    },
    {
     "title": "$node_name - Swap Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) ((max_over_time(node_memory_SwapTotal_bytes{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapTotal_bytes{node_name=~\"$node_name\"}[5m])) -\n(max_over_time(node_memory_SwapFree_bytes{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapFree_bytes{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Used"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (max_over_time(node_memory_SwapFree_bytes{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapFree_bytes{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Free"
      },
      {
       "expr": "avg by (node_name) (max_over_time(node_memory_SwapTotal_bytes{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapTotal_bytes{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$node_name - Swap Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) ((max_over_time(node_memory_SwapTotal_bytes{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapTotal_bytes{node_name=~\"$node_name\"}[5m])) -\n(max_over_time(node_memory_SwapFree_bytes{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapFree_bytes{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Used"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (max_over_time(node_memory_SwapFree_bytes{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapFree_bytes{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Free"
      },
      {
       "expr": "avg by (node_name) (max_over_time(node_memory_SwapTotal_bytes{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapTotal_bytes{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$node_name - Swap Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpin{node_name=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=~\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpout{node_name=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=~\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    },
    {
     "title": "$node_name - Swap Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpin{node_name=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=~\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpout{node_name=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=~\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk partitions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node_name - Mountpoint Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,mountpoint) (1 - (max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])) / \n(max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or\nmax_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])))",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "$node_name - Mountpoint Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,mountpoint) (1 - (max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])) / \n(max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or\nmax_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])))",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "$node_name - Free Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,mountpoint) (max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or\nmax_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m]))",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "$node_name - Free Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,mountpoint) (max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or\nmax_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m]))",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node_name - I/O Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (rate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[5m]) * 1024 or\nsum by (node_name) (max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Page In"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (rate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[5m]) * 1024 or\nsum by (node_name) (max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Page Out"
      }
     ]
    },
    {
     "title": "$node_name - I/O Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (rate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[5m]) * 1024 or\nsum by (node_name) (max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Page In"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (rate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[5m]) * 1024 or\nsum by (node_name) (max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Page Out"
      }
     ]
    },
    {
     "title": "$node_name - Disk Operations",
     "type": "graph",
     "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,device) (rate(node_disk_reads_completed_total{node_name=~'$node_name'}[$interval]) or irate(node_disk_reads_completed_total{node_name=~'$node_name'}[5m]) or (max_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Reads: {{device}}"
      },
      {
       "expr": "avg by (node_name,device) (rate(node_disk_writes_completed_total{node_name=~'$node_name'}[$interval]) or irate(node_disk_writes_completed_total{node_name=~'$node_name'}[5m]) or (max_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Writes: {{device}}"
      }
     ]
    },
    {
     "title": "$node_name - Disk Operations",
     "type": "graph",
     "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,device) (rate(node_disk_reads_completed_total{node_name=~'$node_name'}[$interval]) or irate(node_disk_reads_completed_total{node_name=~'$node_name'}[5m]) or (max_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Reads: {{device}}"
      },
      {
       "expr": "avg by (node_name,device) (rate(node_disk_writes_completed_total{node_name=~'$node_name'}[$interval]) or irate(node_disk_writes_completed_total{node_name=~'$node_name'}[5m]) or (max_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Writes: {{device}}"
      }
     ]
    },
    {
     "title": "$node_name - Disk Bandwidth",
     "type": "graph",
     "description": "Shows volume of reads and writes the storage is handling. This can be better measure of IO capacity usage for network attached and SSD storage as it is often bandwidth limited.  Amount of data being written to the disk can be used to estimate Flash storage life time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,device) (rate(node_disk_read_bytes_total{node_name=~\"$node_name\"}[$interval]) or irate(node_disk_read_bytes_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Reads: {{device}} "
      },
      {
       "expr": "avg by (node_name,device) (rate(node_disk_written_bytes_total{node_name=~\"$node_name\"}[$interval]) or irate(node_disk_written_bytes_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Writes: {{device}} "
      }
     ]
    },
    {
     "title": "$node_name - Disk Bandwidth",
     "type": "graph",
     "description": "Shows volume of reads and writes the storage is handling. This can be better measure of IO capacity usage for network attached and SSD storage as it is often bandwidth limited.  Amount of data being written to the disk can be used to estimate Flash storage life time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,device) (rate(node_disk_read_bytes_total{node_name=~\"$node_name\"}[$interval]) or irate(node_disk_read_bytes_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Reads: {{device}} "
      },
      {
       "expr": "avg by (node_name,device) (rate(node_disk_written_bytes_total{node_name=~\"$node_name\"}[$interval]) or irate(node_disk_written_bytes_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Writes: {{device}} "
      }
     ]
    },
    {
     "title": "$node_name - Disk IO Utilization",
     "type": "graph",
     "description": "Shows disk Utilization as a percentage of the time when there was at least one IO request in flight. It is designed to match utilization available in iostat tool. The graph augments the IO latency and Disk Load Graphs, allowing to determine if the disk load was evenly distributed in time or consuming the IO momentarily. Higher utilization increases the likeliness of IO queuing. Always consider this metric along with response time and IO queue depth.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,device) (rate(node_disk_io_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or irate(node_disk_io_time_seconds_total{node_name=~\"$node_name\"}[5m]) or\n(max_over_time(rdsosmetrics_diskIO_util{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_util{node_name=~\"$node_name\"}[5m]))/100)",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "$node_name - Disk IO Utilization",
     "type": "graph",
     "description": "Shows disk Utilization as a percentage of the time when there was at least one IO request in flight. It is designed to match utilization available in iostat tool. The graph augments the IO latency and Disk Load Graphs, allowing to determine if the disk load was evenly distributed in time or consuming the IO momentarily. Higher utilization increases the likeliness of IO queuing. Always consider this metric along with response time and IO queue depth.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,device) (rate(node_disk_io_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or irate(node_disk_io_time_seconds_total{node_name=~\"$node_name\"}[5m]) or\n(max_over_time(rdsosmetrics_diskIO_util{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_util{node_name=~\"$node_name\"}[5m]))/100)",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "$node_name - Disk Latency",
     "type": "graph",
     "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) ((rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / \nrate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval])) > 0 or \n(irate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[5m]) / \nirate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[5m])) > 0\nor avg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[5m])/1000 or\nmax_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) ((rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / \nrate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval])) > 0 or \n(irate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[5m]) / \nirate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[5m])) > 0\nor (avg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[5m])/1000 or\nmax_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Write: {{ device }}"
      }
     ]
    },
    {
     "title": "$node_name - Disk Latency",
     "type": "graph",
     "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) ((rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / \nrate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval])) > 0 or \n(irate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[5m]) / \nirate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[5m])) > 0\nor avg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[5m])/1000 or\nmax_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) ((rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / \nrate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval])) > 0 or \n(irate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[5m]) / \nirate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[5m])) > 0\nor (avg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[5m])/1000 or\nmax_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Write: {{ device }}"
      }
     ]
    },
    {
     "title": "$node_name - Disk Load",
     "type": "graph",
     "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[5m]) or\nmax_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[5m]) or\nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Write: {{ device }}"
      }
     ]
    },
    {
     "title": "$node_name - Disk Load",
     "type": "graph",
     "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[5m]) or\nmax_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[5m]) or\nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Write: {{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "Bps", "label": "bits out (-) / bits in (+)" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name) (sum by (node_name) (rate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Inbound"
      },
      {
       "expr": "avg by (node_name) (sum by (node_name) (rate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or\nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Outbound"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "Bps", "label": "bits out (-) / bits in (+)" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name) (sum by (node_name) (rate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Inbound"
      },
      {
       "expr": "avg by (node_name) (sum by (node_name) (rate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or\nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Outbound"
      }
     ]
    },
    {
     "title": "Network Utilization Hourly",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "repeat": "node_name",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name) (sum(increase(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[1h])) or\nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Received"
      },
      {
       "expr": "avg by (node_name) (sum(increase(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[1h])) or\nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "Network Utilization Hourly",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name) (sum(increase(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[1h])) or\nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Received"
      },
      {
       "expr": "avg by (node_name) (sum(increase(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[1h])) or\nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  }
 ]
}